/**
 * Database types generated by Supabase CLI
 * Run: pnpm db:generate to update this file
 *
 * This is a placeholder. The actual types will be generated from your Supabase schema.
 */

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_type: 'INDIVIDUAL' | 'INSTITUTIONAL';
          kyc_status: 'PENDING' | 'IN_REVIEW' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
          accreditation_level: 'RETAIL' | 'QUALIFIED' | 'PROFESSIONAL' | null;
          primary_jurisdiction: string | null;
          allowed_jurisdictions: string[];
          kyc_provider_id: string | null;
          kyc_verified_at: string | null;
          kyc_expires_at: string | null;
          aml_status: 'PENDING' | 'IN_REVIEW' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
          aml_last_check: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          legal_name: string;
          tax_id: string;
          jurisdiction: string;
          kyb_status: 'PENDING' | 'IN_REVIEW' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
          licenses: Record<string, unknown>[];
          representatives: string[];
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['organizations']['Row'],
          'id' | 'created_at' | 'updated_at'
        >;
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>;
      };
      assets: {
        Row: {
          id: string;
          issuer_id: string | null;
          asset_type: 'REAL_ESTATE' | 'CREDIT' | 'COMMODITY' | 'EQUITY';
          name: string;
          symbol: string;
          description: string | null;
          underlying_asset: Record<string, unknown>;
          legal_documents: Record<string, unknown>[];
          compliance_rules: Record<string, unknown>;
          eligible_jurisdictions: string[];
          eligible_accreditation: ('RETAIL' | 'QUALIFIED' | 'PROFESSIONAL')[];
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['assets']['Row'],
          'id' | 'created_at' | 'updated_at'
        >;
        Update: Partial<Database['public']['Tables']['assets']['Insert']>;
      };
      site_content: {
        Row: {
          key: string;
          value: string;
          value_type: 'text' | 'json' | 'richtext';
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          key: string;
          value: string;
          value_type?: 'text' | 'json' | 'richtext';
          updated_by?: string | null;
        };
        Update: {
          key?: string;
          value?: string;
          value_type?: 'text' | 'json' | 'richtext';
          updated_by?: string | null;
        };
      };
      // Add more tables as needed...
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_type: 'INDIVIDUAL' | 'INSTITUTIONAL';
      kyc_status: 'PENDING' | 'IN_REVIEW' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
      accreditation_level: 'RETAIL' | 'QUALIFIED' | 'PROFESSIONAL';
      asset_type: 'REAL_ESTATE' | 'CREDIT' | 'COMMODITY' | 'EQUITY';
      offering_status: 'DRAFT' | 'PENDING_APPROVAL' | 'OPEN' | 'CLOSED' | 'CANCELLED';
      order_side: 'BUY' | 'SELL';
      order_type: 'MARKET' | 'LIMIT';
      order_status: 'PENDING' | 'OPEN' | 'PARTIAL' | 'FILLED' | 'CANCELLED';
      wallet_type: 'CUSTODIAL' | 'SELF_CUSTODY';
      chain: 'ETHEREUM' | 'POLYGON' | 'ARBITRUM';
      vault_strategy: 'STAKING' | 'FIXED_INCOME' | 'LENDING' | 'LP_REWARDS';
      vault_status: 'ACTIVE' | 'PAUSED' | 'DEPRECATED';
      loan_status: 'ACTIVE' | 'REPAID' | 'LIQUIDATED' | 'DEFAULTED';
    };
  };
}
